pipeline {
    agent any
    environment{
        DOCKERHUB_CREDS = credentials('12d391d5-89f4-4bd7-814f-4bb63f2816c4')
    }
    stages {
        stage('Clone Repo') {
            steps {
                checkout scm
                sh 'ls *'
            }
        }
        stage('Initialize'){
            def dockerhome = tool 'myDocker'
            env.PATH = "${dockerHome}/bin:${env.PATH}"
        }
        stage('Build Image'){
            steps{
                sh 'docker build -t prabin09/jenkinstest:$BUILD_NUMBER ./pushdockerimage/'
            }
        }
        stage('Docker Login') {
            steps {
                sh 'echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin'
            }
        }
        stage('Docker Push') {
            steps{
                sh 'docker push prabin09/jenkinstest:$BUILD_NUMBER'
            }
        }
    }
    post{
        always {
            sh 'docker logout'
        }
    }
}